/**
 * Run once to seed the music_knowledge table with underground artist entries.
 * Usage: npx tsx supabase/seed_music_knowledge.ts
 *
 * Requires in .env.local or environment:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 *   OPENAI_API_KEY
 */

import { createClient } from '@supabase/supabase-js'
import OpenAI from 'openai'
import dotenv from 'dotenv'
import { resolve } from 'path'

console.log('cwd:', process.cwd())
const envPath = resolve(process.cwd(), '.env.local')
console.log('Loading env from:', envPath)
const envResult = dotenv.config({ path: envPath })
if (envResult.error) {
  console.error('dotenv error:', envResult.error.message)
} else {
  console.log('dotenv parsed keys:', Object.keys(envResult.parsed ?? {}))
}

// Pre-flight check
const REQUIRED = ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'OPENAI_API_KEY']
const missing = REQUIRED.filter((k) => !process.env[k])
if (missing.length > 0) {
  console.error('Missing required env vars:', missing.join(', '))
  console.error('Make sure these are set in .env.local')
  process.exit(1)
}

console.log('Env loaded:')
console.log('  SUPABASE_URL:', process.env.NEXT_PUBLIC_SUPABASE_URL?.slice(0, 30) + '...')
console.log('  SERVICE_ROLE_KEY:', process.env.SUPABASE_SERVICE_ROLE_KEY?.slice(0, 10) + '...')
console.log('  OPENAI_API_KEY:', process.env.OPENAI_API_KEY?.slice(0, 10) + '...')

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })

interface ArtistRecord {
  artist_name: string
  style_description: string
  associated_genres: string[]
  typical_bpm_range: string
  mood_tags: string[]
  underground_level: number
  era: string
  similar_artists: string[]
}

const ARTISTS: ArtistRecord[] = [
  {
    artist_name: 'Osamason',
    style_description: `Osamason is a defining artist of the 2020s SoundCloud underground, operating at the intersection of rage, plugg, and melodic trap. His music is characterized by slow, dragging 808 patterns, hazy synth textures, and an emotional delivery that blends vulnerability with detachment. Beats in his lane feature heavily reverbed melodic loops, distorted sub-bass that sits low in the mix, and drums that feel sluggish and deliberate rather than energetic. BPMs typically fall between 65 and 85. Osamason's aesthetic is deeply lo-fi — intentionally raw production choices that feel like music recorded in a small bedroom late at night. He represents the core of the current SoundCloud underground ecosystem where emotional honesty and sonic minimalism are more valued than technical polish or commercial appeal. Producers making beats for his style should focus on restraint: one melodic element, slow rolling 808, and generous use of reverb and space.`,
    associated_genres: ['Plugg', 'Rage', 'SoundCloud Rap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Melancholy', 'Introspective', 'Dark', 'Dreamy'],
    underground_level: 10,
    era: '2021-present',
    similar_artists: ['Nettspend', 'Yhapojj', 'Ethereal', 'SSGKobe'],
  },
  {
    artist_name: 'Nettspend',
    style_description: `Nettspend is one of the most talked-about artists in the 2020s SoundCloud underground, known for an intensely emotional melodic style built on rage and plugg production. His music features slow, hypnotic beats with woozy synth melodies, sliding 808s, and a generally melancholic atmosphere that has resonated widely across the underground. BPMs typically fall between 70 and 90. Nettspend's vocal delivery — half-sung, half-rapped with heavy autotune — mirrors the dreamlike quality of his production choices. His beats are defined by a floating, weightless quality where nothing feels anchored or permanent. Producers working in his aesthetic should prioritize melody above all: a single haunting synth line, slow dragging 808 with pitch slides, and drum patterns so minimal they feel like afterthoughts. The emotional register is consistently melancholy and yearning, music for processing feeling rather than expressing aggression.`,
    associated_genres: ['Rage', 'Plugg', 'Melodic Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Melancholy', 'Dreamy', 'Emotional', 'Hypnotic'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Osamason', 'Yhapojj', 'SSGKobe', 'Summrs'],
  },
  {
    artist_name: 'Che (cheRomani+)',
    style_description: `Che, also known as cheRomani+, is an underground SoundCloud artist who blends rage and plugg aesthetics with a more experimental, genre-fluid sensibility. His music incorporates unconventional melodic choices, glitchy production elements, and a willingness to push the sonic boundaries of the plugg format. Beats in his lane feature pitched-down or warped synth textures, slow 808 patterns, and a general sense of audio disorientation that distinguishes his work from more straightforward rage music. BPMs range from 65 to 85. Che's aesthetic reflects the experimental edge of the SoundCloud underground — artists who use the plugg template as a starting point rather than a rigid formula. Producers referencing his style should embrace imperfection, warped audio, and unexpected melodic choices that feel wrong at first but ultimately click.`,
    associated_genres: ['Plugg', 'Rage', 'Experimental Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Dark', 'Experimental', 'Dreamy', 'Disorienting'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Maajins'],
  },
  {
    artist_name: 'Nine Vicious',
    style_description: `Nine Vicious is an underground SoundCloud artist who brings a harder, more aggressive energy to the rage and plugg scene. While operating within the same sonic universe as his peers — slow 808s, reverb-heavy melodies, lo-fi production — his music carries a more threatening undertone that connects the plugg aesthetic to harder trap traditions. BPMs fall between 70 and 95. Nine Vicious represents the darker, more menacing end of the SoundCloud underground spectrum, where the dreamlike quality of plugg music meets a visceral aggression. Beats for his style should have weight and presence — not the ultra-minimal floating style of the softest plugg but something with more low-end density and a sense of latent danger.`,
    associated_genres: ['Rage', 'Dark Trap', 'Plugg'],
    typical_bpm_range: '70-95',
    mood_tags: ['Dark', 'Aggressive', 'Menacing', 'Heavy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Slayr', 'Homixide Gang'],
  },
  {
    artist_name: 'Slayr',
    style_description: `Slayr is an underground SoundCloud artist operating in the rage and plugg space with a style that emphasizes dark, aggressive energy layered over hypnotic slow beats. His music occupies the intersection of the SoundCloud underground and harder trap traditions, creating a sound that is simultaneously threatening and emotionally resonant. Beats in his lane feature slow, deliberate 808 patterns, sinister melodic loops, and a production aesthetic that values atmosphere over technical complexity. BPMs typically fall between 70 and 90. Slayr's work represents a vision of underground rap where aggression and melancholy coexist — the beats are slow enough to feel contemplative but dark enough to feel dangerous.`,
    associated_genres: ['Rage', 'Plugg', 'Dark Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Dark', 'Aggressive', 'Menacing', 'Hypnotic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nine Vicious', 'Osamason', 'Nettspend'],
  },
  {
    artist_name: 'Maajins',
    style_description: `Maajins is an underground SoundCloud artist whose music blends plugg and rage aesthetics with a distinctly ethereal, otherworldly quality. His production leans heavily into ambient textures — reverb-saturated synth pads, distant melodic elements, and 808s that feel like they are coming from another dimension. BPMs fall between 60 and 80. Maajins represents the most atmospheric wing of the plugg underground, where beats function more as sonic environments than rhythmic foundations. The music feels weightless and suspended in time, creating a listening experience that is deeply introspective and somewhat dissociative. Producers referencing his aesthetic should prioritize texture and atmosphere above all — the goal is to create a mood, not to drive energy.`,
    associated_genres: ['Plugg', 'Ambient Trap', 'Rage'],
    typical_bpm_range: '60-80',
    mood_tags: ['Ethereal', 'Dreamy', 'Atmospheric', 'Introspective'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Che (cheRomani+)', 'Nettspend'],
  },
  {
    artist_name: 'Bleood',
    style_description: `Bleood is an underground SoundCloud artist working in the rage and plugg tradition with a sound that emphasizes raw, unpolished production and emotional vulnerability. His music features the characteristic plugg elements — slow 808s, hazy melodic loops, reverb-heavy mix — but with a particularly raw and exposed quality that feels genuinely intimate. BPMs fall between 65 and 85. Bleood represents the bedroom-production ethos of the SoundCloud underground at its most pure: music that sounds like it was made in one session, driven by feeling rather than craft, and valued for its emotional honesty over its technical execution. Beats for his style should feel deliberately unfinished, with audible imperfections that add to rather than detract from the overall atmosphere.`,
    associated_genres: ['Plugg', 'Rage', 'Lo-Fi Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Raw', 'Emotional', 'Vulnerable', 'Melancholy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Maajins', 'Nettspend'],
  },
  {
    artist_name: 'Wegonebeok',
    style_description: `Wegonebeok is an underground SoundCloud artist who brings a melodic, emotionally resonant quality to the rage and plugg aesthetic. His music is defined by hazy, dreamy production — synth melodies that drift rather than assert themselves, 808 bass that moves with a slow inevitability, and drums that feel like they are barely holding the track together. BPMs fall between 65 and 85. Wegonebeok's name reflects his artistic sensibility: a sense of forward motion and resolution that is always just slightly out of reach. His music communicates a specific feeling of wistful longing that has become central to the 2020s plugg aesthetic. Beats referencing his style should create the feeling of motion without destination — slow, melodic, and emotionally open.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Dreamy', 'Melancholy', 'Wistful', 'Hypnotic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Osamason', 'Yhapojj'],
  },
  {
    artist_name: 'S3bby',
    style_description: `S3bby is an underground SoundCloud rapper whose music blends rage and plugg production with a melodic sensibility that draws from both hip-hop and more experimental electronic music. His beats are characterized by layered synth textures, slow-rolling 808 patterns, and a generally hazy, intoxicated atmosphere. BPMs fall between 70 and 90. S3bby represents a strain of the SoundCloud underground where the rage aesthetic begins to absorb influences from shoegaze, emo, and ambient music — creating a hybrid that feels distinctly post-genre. His music has a textural richness that rewards close listening, with multiple sonic layers that reveal themselves gradually.`,
    associated_genres: ['Rage', 'Plugg', 'Experimental Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Hazy', 'Dreamy', 'Melancholy', 'Layered'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Che (cheRomani+)'],
  },
  {
    artist_name: 'R8',
    style_description: `R8 is an underground SoundCloud artist working in the plugg and rage aesthetic with a minimalist approach that strips the format down to its essential elements. His beats feature single melodic lines, slow 808 patterns, and very sparse drum programming that creates an almost meditative quality. BPMs fall between 65 and 85. R8's production philosophy is one of extreme restraint — where other artists might add layers, he removes them. The resulting music feels suspended and still, with each element given maximum space to breathe. This minimalist approach creates an emotional intensity through negative space rather than sonic density, making his music feel both simple and psychologically weighty.`,
    associated_genres: ['Plugg', 'Rage', 'Minimalist Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Minimalist', 'Dark', 'Meditative', 'Sparse'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Maajins', 'Osamason', 'Bleood'],
  },
  {
    artist_name: 'Xaviersobased',
    style_description: `Xaviersobased is an underground SoundCloud artist known for a uniquely colorful, almost psychedelic take on the rage and plugg aesthetic. While many of his peers embrace pure darkness, Xavier incorporates brighter melodic elements and a more playful energy that creates an unusual contrast with the slow, heavy production typical of the genre. BPMs fall between 70 and 90. His music communicates a sense of chaotic joy filtered through a drugged-out, distorted lens — beats that feel simultaneously happy and deeply unsettled. The production features warped synth melodies, distorted 808s, and a mixing aesthetic that embraces clipping and saturation as expressive tools. Producers referencing his style should lean into contrast: bright melodies over heavy bass, playful rhythms under a menacing atmosphere.`,
    associated_genres: ['Rage', 'Plugg', 'Hyperpop Adjacent'],
    typical_bpm_range: '70-90',
    mood_tags: ['Chaotic', 'Colorful', 'Dark', 'Playful'],
    underground_level: 10,
    era: '2021-present',
    similar_artists: ['Nettspend', 'Osamason', 'Sickboyrari'],
  },
  {
    artist_name: '1oneam',
    style_description: `1oneam is an underground SoundCloud artist whose name reflects the late-night, insomniac energy of his music. His beats are built for listening at 1am alone — slow, contemplative, deeply melancholic production that feels like a conversation with yourself at the end of a long night. BPMs fall between 60 and 80. The production features the characteristic plugg elements (slow 808, reverb-heavy melody, minimal drums) filtered through a particularly late-night, isolationist lens. There is a rawness to 1oneam's music that connects to the confessional tradition of bedroom rap while remaining firmly rooted in the SoundCloud underground aesthetic.`,
    associated_genres: ['Plugg', 'Rage', 'Lo-Fi Trap'],
    typical_bpm_range: '60-80',
    mood_tags: ['Melancholy', 'Introspective', 'Lonely', 'Late-Night'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Bleood', 'Maajins'],
  },
  {
    artist_name: 'ohsxnta',
    style_description: `ohsxnta is an underground SoundCloud artist working in the intersection of rage, plugg, and more experimental territory. His music blends the slow 808 patterns and reverb-heavy aesthetics of the plugg underground with unconventional melodic choices and production textures that push against genre conventions. BPMs fall between 65 and 85. ohsxnta represents a creative strain of the SoundCloud underground where technical experimentation and emotional authenticity coexist — artists who are fluent in the genre's language but use it to say something personal rather than formulaic. His beats carry a sense of searching and incompleteness that makes them feel alive and in process.`,
    associated_genres: ['Plugg', 'Rage', 'Experimental'],
    typical_bpm_range: '65-85',
    mood_tags: ['Experimental', 'Melancholy', 'Searching', 'Dark'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Che (cheRomani+)', 'S3bby', 'Maajins'],
  },
  {
    artist_name: 'Rexv2',
    style_description: `Rexv2 is an underground SoundCloud artist who brings a high-energy, aggressive dimension to the rage and plugg aesthetic. His music features the slow 808 foundation typical of plugg but layered with more abrasive, distorted melodic elements and a vocal delivery that carries genuine menace. BPMs fall between 70 and 95. Rexv2's production aesthetic bridges the gap between the slow, hypnotic end of plugg and the harder, more confrontational end of dark trap — creating music that feels threatening without sacrificing the dreamy quality central to the genre. His beats have a deliberately unpolished quality that emphasizes authenticity over technical precision.`,
    associated_genres: ['Rage', 'Plugg', 'Dark Trap'],
    typical_bpm_range: '70-95',
    mood_tags: ['Aggressive', 'Dark', 'Raw', 'Menacing'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nine Vicious', 'Slayr', 'Osamason'],
  },
  {
    artist_name: 'Pradabagshawty',
    style_description: `Pradabagshawty is an underground SoundCloud artist who combines the plugg and rage aesthetic with a fashion-forward, luxury-referencing persona that creates an interesting tension between high-end aspirations and lo-fi, underground production. Her beats feature slow 808 patterns, hazy melodic textures, and a generally cool, detached emotional register that reflects both the plugg tradition and a distinctly feminine perspective on the genre. BPMs fall between 70 and 85. Pradabagshawty represents a generation of artists who are expanding the traditionally male-dominated plugg scene with perspectives and aesthetics that push the genre in new directions.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Cool', 'Detached', 'Dark', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Bktherula'],
  },
  {
    artist_name: 'Boolymon',
    style_description: `Boolymon is an underground SoundCloud artist whose music blends the plugg and rage aesthetic with a harder, street-influenced sensibility. His beats carry more rhythmic drive than the most minimalist plugg producers, with 808 patterns that have a propulsive quality alongside the characteristic slow tempo. BPMs fall between 75 and 95. Boolymon's sound sits at the intersection of SoundCloud underground culture and street rap, creating music that is simultaneously hypnotic and hard. The production features dark melodic loops, punchy 808 patterns, and a mixing aesthetic that emphasizes bass weight and presence over atmospheric softness.`,
    associated_genres: ['Rage', 'Plugg', 'Street Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Hard', 'Dark', 'Aggressive', 'Driving'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Slayr', 'Nine Vicious', 'Rexv2'],
  },
  {
    artist_name: 'TDF',
    style_description: `TDF is an underground SoundCloud collective or artist whose music occupies the atmospheric, experimental wing of the plugg and rage underground. The sound is characterized by layered ambient textures, slow-moving 808 patterns, and a production aesthetic that values mood and atmosphere above conventional song structure. BPMs fall between 60 and 80. TDF represents the most experimental and least commercially accessible corner of the SoundCloud underground — music that feels more like sound design than traditional rap production but carries an emotional intensity that transcends genre. Producers referencing this aesthetic should think in terms of sonic environments rather than beat structures.`,
    associated_genres: ['Plugg', 'Ambient Trap', 'Experimental'],
    typical_bpm_range: '60-80',
    mood_tags: ['Atmospheric', 'Experimental', 'Dark', 'Ambient'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Maajins', 'ohsxnta', 'Che (cheRomani+)'],
  },
  {
    artist_name: 'Fakemink',
    style_description: `Fakemink is an underground SoundCloud artist who blends the plugg and rage aesthetic with elements of hyperpop and digital maximalism. His music features the slow 808 foundation of plugg alongside pitched-up vocal chops, glitchy digital artifacts, and melodic elements that lean toward the pop and hyperpop end of the underground spectrum. BPMs fall between 70 and 90. Fakemink represents a generation of SoundCloud artists who grew up listening to both plugg rap and hyperpop simultaneously, creating a synthesis that feels uniquely 2020s. His beats have a deliberately artificial, digital quality where nothing is meant to sound organic or natural.`,
    associated_genres: ['Plugg', 'Hyperpop', 'Rage'],
    typical_bpm_range: '70-90',
    mood_tags: ['Glitchy', 'Digital', 'Dark', 'Chaotic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Xaviersobased', 'Sickboyrari', 'Nettspend'],
  },
  {
    artist_name: '2Slimey',
    style_description: `2Slimey is an underground SoundCloud artist whose music brings a cooler, more detached energy to the plugg and rage aesthetic. The "slimey" persona reflects a certain emotional slipperiness — beats that feel smooth and dangerous simultaneously, with 808 patterns that slide and bend beneath hazy melodic loops. BPMs fall between 70 and 90. 2Slimey's production has a cinematic quality where the music feels like a soundtrack to something slightly illicit happening in slow motion. The production features deep, resonant 808s, cool melodic synth lines, and a general sense of controlled menace that distinguishes his sound from more explicitly aggressive rage artists.`,
    associated_genres: ['Plugg', 'Rage', 'Dark Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Cool', 'Menacing', 'Smooth', 'Dark'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'BabyBartier', 'Nettspend'],
  },
  {
    artist_name: 'Okaymar',
    style_description: `Okaymar is an underground SoundCloud artist who applies the plugg and rage framework to a more melodically adventurous style than many of his contemporaries. His beats feature unusual chord progressions and synth choices that push beyond the typical plugg palette while maintaining the genre's essential slow tempo and atmospheric quality. BPMs fall between 65 and 85. Okaymar represents artists in the SoundCloud underground who are expanding the genre's sonic possibilities through musical curiosity and a willingness to experiment with production choices that might feel wrong at first but ultimately deepen the emotional impact.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Melodic', 'Experimental', 'Dreamy', 'Emotional'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Osamason', 'S3bby'],
  },
  {
    artist_name: 'Izaya Tiji',
    style_description: `Izaya Tiji is an underground SoundCloud artist known for an intensely emotional, melodic approach to rage and plugg music. His music carries a sense of raw feeling that feels almost uncomfortably exposed — beats built on slow, mournful melodies and 808 patterns that feel like a physical manifestation of sadness. BPMs fall between 65 and 85. Izaya Tiji occupies the most emotionally vulnerable corner of the rage underground, where the music's primary function is cathartic release rather than energy or aggression. His beats have a confessional quality that connects to the emo-rap tradition while remaining firmly in the SoundCloud plugg aesthetic. Producers referencing his style should aim for maximum emotional impact with minimum sonic complexity.`,
    associated_genres: ['Plugg', 'Rage', 'Emo Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Emotional', 'Melancholy', 'Vulnerable', 'Raw'],
    underground_level: 10,
    era: '2021-present',
    similar_artists: ['Nettspend', 'Osamason', 'Wegonebeok'],
  },
  {
    artist_name: 'Swapa',
    style_description: `Swapa is an underground SoundCloud artist who blends plugg and rage aesthetics with a more rhythmically engaging style that retains the genre's atmospheric quality while adding more bounce and movement to the drum patterns. BPMs fall between 75 and 95. Swapa represents artists in the SoundCloud underground who are finding ways to make plugg music feel more dynamic without sacrificing its essential dreamlike atmosphere. His beats feature the characteristic slow 808 and reverb-heavy melody but with drum patterns that carry more rhythmic interest and propulsive energy.`,
    associated_genres: ['Plugg', 'Rage', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Dark', 'Energetic', 'Melodic', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Boolymon', 'Nettspend'],
  },
  {
    artist_name: 'Untiljapan',
    style_description: `Untiljapan is an underground SoundCloud artist whose name suggests a geographic and cultural restlessness that is reflected in the music. His beats draw from the plugg and rage tradition but incorporate subtle influences from Japanese popular music, anime soundtracks, and J-pop melodic sensibilities that create a distinctly internationalist take on the American underground. BPMs fall between 65 and 85. Untiljapan represents the global dimension of the SoundCloud underground — artists who absorb influences from across cultures and blend them into a sound that feels simultaneously local and universal. His production has a sweetness and melodic richness that distinguishes it from more purely dark plugg aesthetics.`,
    associated_genres: ['Plugg', 'Rage', 'J-Influenced Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Dreamy', 'Melodic', 'Sweet', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Osamason', 'Fakemink'],
  },
  {
    artist_name: 'Prettifun',
    style_description: `Prettifun is an underground SoundCloud artist whose name encapsulates the paradox at the heart of much plugg music — something that sounds beautiful while communicating pain. Her beats feature delicate, melodic synth lines over slow 808 patterns, creating a sound that is simultaneously pretty and melancholy. BPMs fall between 65 and 85. Prettifun represents the feminine perspective in the plugg underground, bringing a sensitivity and emotional directness to the genre that expands its expressive range. Her production has a crystalline quality where individual melodic elements feel precious and carefully chosen, creating a sense of something fragile at the center of the music.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Delicate', 'Melancholy', 'Sweet', 'Emotional'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Pradabagshawty', 'Osamason', 'Nettspend'],
  },
  {
    artist_name: '1300Saint',
    style_description: `1300Saint is an underground SoundCloud artist who brings a spiritual and aspirational dimension to the rage and plugg aesthetic. His music carries themes of elevation and transcendence filtered through the slow, hypnotic production of the underground — as if prayer and street life occupy the same sonic space. BPMs fall between 70 and 90. The production features slow, reverb-heavy beats with melodic elements that carry both darkness and a kind of yearning beauty. 1300Saint represents artists in the SoundCloud underground who use the genre's introspective qualities to explore questions of meaning, identity, and aspiration alongside the more common themes of emotional pain.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Spiritual', 'Aspirational', 'Dark', 'Introspective'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Izaya Tiji'],
  },
  {
    artist_name: 'LazerDim700',
    style_description: `LazerDim700 is an underground SoundCloud rapper who brings a faster, more energetic sensibility to the rage scene without abandoning its essential darkness. His beats feature more rhythmically complex drum patterns than typical plugg music, with BPMs in the 90-115 range that create a more urgent, forward-moving energy. The production still carries the reverb-heavy melodic textures and distorted 808s characteristic of the underground, but at a tempo that allows for more aggressive and technically complex rapping styles. LazerDim700 represents artists who are pushing the rage aesthetic toward higher energy and greater rhythmic complexity while maintaining its underground credibility.`,
    associated_genres: ['Rage', 'Trap', 'Underground Hip-Hop'],
    typical_bpm_range: '90-115',
    mood_tags: ['Energetic', 'Dark', 'Aggressive', 'Fast'],
    underground_level: 9,
    era: '2021-present',
    similar_artists: ['Homixide Gang', 'Bktherula', 'UnoTheActivist'],
  },
  {
    artist_name: 'Glokk40Spaz',
    style_description: `Glokk40Spaz is an underground Chicago rapper whose music blends Chicago drill traditions with a more chaotic, unhinged energy that has earned him recognition in the broader underground rap community. His production features hard-hitting drums, aggressive 808 patterns, and a general sense of barely-controlled chaos that is distinctly Chicago but pushes beyond the genre's established conventions. BPMs fall between 130 and 155. His vocal style — rapid-fire and unpredictable — demands beats with space for spontaneous energy. The production aesthetic is gritty and rough, with a lo-fi quality that reflects underground Chicago recording culture. Glokk40Spaz represents artists who take regional drill traditions and push them to more extreme and experimental places.`,
    associated_genres: ['Chicago Drill', 'Trap', 'Dark Rap'],
    typical_bpm_range: '130-155',
    mood_tags: ['Chaotic', 'Aggressive', 'Dark', 'Energetic'],
    underground_level: 8,
    era: '2020-present',
    similar_artists: ['Homixide Gang', 'LazerDim700', 'UnoTheActivist'],
  },
  {
    artist_name: 'Yhapojj',
    style_description: `Yhapojj is one of the most distinctive voices in the 2020s plugg and rage underground, known for an extremely slow, almost paralyzed tempo and a production aesthetic that takes minimalism to its logical extreme. His beats crawl at 55-75 BPM — slower than most plugg music — with single melodic elements that hover in long, sustained notes and 808 patterns that feel like they are barely moving. The emotional register is one of profound dissociation and numbness, music that sounds like depression rendered in sonic form. Yhapojj has influenced a generation of producers who understand that tempo restraint and space can create more emotional impact than density or complexity. Key features: extremely slow tempo, single sustained melodic element, minimal drums, overwhelming reverb.`,
    associated_genres: ['Plugg', 'Rage', 'Ambient Trap'],
    typical_bpm_range: '55-75',
    mood_tags: ['Dissociated', 'Numb', 'Melancholy', 'Slow'],
    underground_level: 10,
    era: '2020-present',
    similar_artists: ['Osamason', 'Nettspend', 'Maajins', 'SSGKobe'],
  },
  {
    artist_name: 'Jaydes',
    style_description: `Jaydes is an underground SoundCloud artist working in the plugg and rage tradition with a particularly melodic and emotionally open style. His beats feature carefully constructed synth melodies over slow 808 patterns, with a production quality that feels intentional and considered rather than purely improvisational. BPMs fall between 70 and 85. Jaydes represents artists in the SoundCloud underground who bring a degree of musical sophistication to the genre without sacrificing its essential lo-fi, emotional character. His production has a gentle quality that distinguishes it from harder rage music while remaining unmistakably rooted in the underground aesthetic.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Melodic', 'Gentle', 'Emotional', 'Dreamy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Izaya Tiji', 'Prettifun'],
  },
  {
    artist_name: 'Rekover Jet',
    style_description: `Rekover Jet is an underground SoundCloud artist whose music suggests movement and escape — beats that feel like they are always in transit, never quite arriving. His production features rhythmic elements that provide more forward momentum than typical plugg music while retaining the genre's atmospheric and emotional qualities. BPMs fall between 75 and 95. Rekover Jet represents a strain of the underground where the plugg aesthetic is used to narrate experiences of motion, change, and seeking rather than pure introspective stillness. His beats carry a cinematic quality — production that would soundtrack a drive to somewhere unknown at night.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Cinematic', 'Moving', 'Dark', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Swapa'],
  },
  {
    artist_name: 'Nino Paid',
    style_description: `Nino Paid is an underground SoundCloud artist who blends plugg and rage aesthetics with a more explicitly street and hustle-oriented perspective. His music combines the slow, hypnotic production of the underground with themes and energy that connect to harder street rap traditions. BPMs fall between 75 and 95. The beats feature dark melodic loops, heavy 808 patterns, and a production aesthetic that sits between the dreamlike quality of pure plugg and the more grounded aggression of street rap. Nino Paid represents artists who use the underground's sonic tools to tell stories rooted in material reality rather than pure emotional abstraction.`,
    associated_genres: ['Plugg', 'Rage', 'Street Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Hard', 'Dark', 'Gritty', 'Driven'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Boolymon', 'Nine Vicious', 'Rexv2'],
  },
  {
    artist_name: 'Jaeychino',
    style_description: `Jaeychino is an underground SoundCloud artist who brings a melodic and emotionally complex sensibility to the plugg and rage aesthetic. His music features layered vocal harmonies over slow production, creating a sound that is simultaneously more texturally rich than typical plugg and emotionally more nuanced. BPMs fall between 70 and 85. Jaeychino represents artists who are expanding the sonic possibilities of the underground by incorporating melodic techniques from R&B and soul into the plugg framework — music that references multiple Black musical traditions simultaneously.`,
    associated_genres: ['Plugg', 'Rage', 'R&B Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Melodic', 'Emotional', 'Rich', 'Dreamy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Izaya Tiji', 'Osamason'],
  },
  {
    artist_name: 'SouthsideSilhouette',
    style_description: `SouthsideSilhouette is an underground SoundCloud artist whose name evokes the shadow aesthetics and geographic specificity of Southern underground rap. His music blends plugg and rage elements with a distinctly Southern sensibility — slower tempos, more emphasis on bass, and a general atmospheric heaviness that connects to Memphis rap and Southern trap traditions. BPMs fall between 65 and 85. SouthsideSilhouette represents the Southern wing of the SoundCloud underground, where the plugg aesthetic meets the Memphis phonk tradition and creates something that feels geographically rooted while remaining sonically contemporary.`,
    associated_genres: ['Plugg', 'Southern Trap', 'Dark Trap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Dark', 'Southern', 'Heavy', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Ethereal', 'Black Kray'],
  },
  {
    artist_name: 'Tezzus',
    style_description: `Tezzus is an underground SoundCloud rapper known for an energetic, rapid-fire delivery over beats that blend the rage and plugg aesthetic with higher energy trap production. His music bridges the slow, hypnotic world of pure plugg and the more aggressive, fast-paced territory of hard trap — beats that carry atmospheric depth at tempos that allow for more dynamic performances. BPMs fall between 85 and 110. Tezzus represents artists who use the sonic language of the underground — reverb, distortion, dark melodies — at tempos and energy levels that feel more actively aggressive than meditative. His production has a raw, energetic quality that rewards high-volume listening.`,
    associated_genres: ['Rage', 'Trap', 'Underground Hip-Hop'],
    typical_bpm_range: '85-110',
    mood_tags: ['Energetic', 'Raw', 'Dark', 'Aggressive'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['LazerDim700', 'Homixide Gang', 'Bktherula'],
  },
  {
    artist_name: 'Milan',
    style_description: `Milan is an underground SoundCloud artist who applies the plugg and rage aesthetic to a more introspective and personal storytelling style. His beats feature slow 808 patterns and hazy melodic loops that create space for intimate lyrical content — music that feels like a private journal entry rendered in sound. BPMs fall between 70 and 85. Milan represents the confessional wing of the underground, where the genre's atmospheric and minimalist qualities are used to create emotional intimacy rather than stylistic posturing. His production has a warmth and personal quality that distinguishes it from colder, more abstract plugg aesthetics.`,
    associated_genres: ['Plugg', 'Rage', 'Introspective Rap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Intimate', 'Personal', 'Warm', 'Melancholy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Izaya Tiji', 'Nettspend', 'Osamason'],
  },
  {
    artist_name: 'Luracks',
    style_description: `Luracks is an underground SoundCloud artist whose music blends the rage and plugg aesthetic with an experimental production approach that incorporates unusual sample sources and unconventional sonic textures. His beats feel like they are assembled from found sounds and unexpected musical fragments rather than purpose-built production elements, giving them a collage-like quality that stands out in the plugg underground. BPMs fall between 65 and 85. Luracks represents the experimental and avant-garde wing of the SoundCloud underground, where the tools of plugg music are used to make something that sounds genuinely strange and original.`,
    associated_genres: ['Plugg', 'Experimental Trap', 'Rage'],
    typical_bpm_range: '65-85',
    mood_tags: ['Experimental', 'Strange', 'Dark', 'Collage'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Che (cheRomani+)', 'ohsxnta', 'TDF'],
  },
  {
    artist_name: 'BabyBartier',
    style_description: `BabyBartier is an underground SoundCloud artist whose name references luxury fashion and whose music blends the rage and plugg aesthetic with an aspirational, high-fashion persona. His beats feature the characteristic slow 808 patterns and reverb-heavy melodic loops of the plugg underground alongside a cool, detached emotional register that reflects his fashion-forward identity. BPMs fall between 70 and 85. BabyBartier represents artists who are expanding the cultural territory of the plugg underground beyond pure emotional expression to encompass fashion, luxury, and lifestyle as artistic themes. His production has a polished sheen within its lo-fi framework that distinguishes it from more purely raw underground aesthetics.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Cool', 'Aspirational', 'Dark', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['2Slimey', 'Pradabagshawty', 'Osamason'],
  },
  {
    artist_name: 'Hxldr',
    style_description: `Hxldr is an underground SoundCloud artist whose music operates at the darker, more aggressive end of the rage and plugg spectrum. His beats feature distorted 808 patterns, menacing melodic loops, and a production aesthetic that emphasizes weight and darkness over the more dreamlike qualities typical of softer plugg music. BPMs fall between 75 and 95. Hxldr's sound sits between plugg's atmospheric minimalism and the confrontational aggression of hard trap, creating a listening experience that is simultaneously hypnotic and threatening. The name itself suggests someone who holds something dangerous — a quality that is reflected throughout his sonic output.`,
    associated_genres: ['Rage', 'Dark Trap', 'Plugg'],
    typical_bpm_range: '75-95',
    mood_tags: ['Dark', 'Menacing', 'Heavy', 'Threatening'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Slayr', 'Nine Vicious', 'Rexv2'],
  },
  {
    artist_name: "Pz'",
    style_description: `Pz' is an underground SoundCloud artist whose abbreviated name reflects the compressed, efficient aesthetic of much SoundCloud underground music — maximum emotional impact in minimal form. His beats feature the essential elements of plugg and rage stripped to their core: slow 808, single melody, reverb. BPMs fall between 65 and 80. Pz' represents the ultra-minimalist wing of the SoundCloud underground where the goal is to find the simplest possible sonic arrangement that carries the maximum emotional weight. His production demonstrates that in the plugg tradition, what you leave out is more important than what you put in.`,
    associated_genres: ['Plugg', 'Rage', 'Minimalist Trap'],
    typical_bpm_range: '65-80',
    mood_tags: ['Minimalist', 'Dark', 'Introspective', 'Sparse'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['R8', 'Maajins', 'Yhapojj'],
  },
  {
    artist_name: 'Dragnutz',
    style_description: `Dragnutz is an underground SoundCloud artist who brings a chaotic, unpredictable energy to the plugg and rage aesthetic. His music features production that feels deliberately destabilized — beats that shift unexpectedly, melodies that go where you don't expect, and a general sense of controlled chaos that keeps the listener off-balance. BPMs fall between 70 and 95. Dragnutz represents the most volatile and unpredictable end of the SoundCloud underground, where the conventions of plugg music are treated as constraints to be subverted rather than formulas to follow. His beats feel alive and dangerous in a way that more formulaic plugg production doesn't.`,
    associated_genres: ['Rage', 'Experimental Trap', 'Plugg'],
    typical_bpm_range: '70-95',
    mood_tags: ['Chaotic', 'Unpredictable', 'Dark', 'Volatile'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Luracks', 'Che (cheRomani+)', 'Xaviersobased'],
  },
  {
    artist_name: 'MexikoDro',
    style_description: `MexikoDro is an Atlanta-based SoundCloud rapper known for one of the most distinctive and melancholy voices in the underground. His self-produced and co-produced beats feature slow, woozy trap production — 808 patterns with significant pitch bend, hazy synth melodies, and a mixing aesthetic that sounds perpetually intoxicated. BPMs typically fall between 75 and 100. MexikoDro's emotional register is uniquely his own: not the dramatic sadness of emo rap or the detached coolness of cloud rap, but something genuinely bleak and resigned. His music sounds like someone who has accepted something difficult and learned to live with it. He has collaborated with artists including Ethereal and is deeply embedded in the Atlanta underground ecosystem. Key features: pitched 808s, woozy melodies, slow-mid tempo, emotionally desolate atmosphere.`,
    associated_genres: ['SoundCloud Rap', 'Plugg', 'Melodic Trap'],
    typical_bpm_range: '75-100',
    mood_tags: ['Desolate', 'Woozy', 'Melancholy', 'Resigned'],
    underground_level: 9,
    era: '2016-present',
    similar_artists: ['Ethereal', 'Black Kray', 'WiFiGawd', 'Osamason'],
  },
  {
    artist_name: 'StoopidXool',
    style_description: `StoopidXool is an underground SoundCloud artist whose name plays with ironic self-deprecation and whose music reflects a similar paradox — music that sounds effortless but carries real emotional weight. His beats feature the plugg and rage aesthetic rendered with a casual, improvisational quality — as if the music appeared naturally rather than being constructed. BPMs fall between 70 and 90. StoopidXool represents the laid-back, low-effort aesthetic of the SoundCloud underground where perceived coolness and authenticity come from apparent effortlessness. The production has a cool, detached quality that masks genuine emotional content.`,
    associated_genres: ['Plugg', 'Rage', 'SoundCloud Rap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Cool', 'Casual', 'Dark', 'Detached'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'BabyBartier'],
  },
  {
    artist_name: 'CashCache',
    style_description: `CashCache is an underground SoundCloud artist who blends the plugg and rage aesthetic with themes of financial hustle and accumulation — music where the slow, hypnotic underground production serves as backdrop for narratives about money, movement, and street economics. BPMs fall between 75 and 95. CashCache represents artists who bring a more materially grounded perspective to the abstract emotional world of plugg music, connecting underground aesthetics to more conventional rap themes. His production carries the characteristic atmospheric quality of the underground while featuring more rhythmically driven elements that reflect the music's more active lyrical content.`,
    associated_genres: ['Plugg', 'Rage', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Driven', 'Dark', 'Energetic', 'Hustle'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Nino Paid', 'Boolymon', '2Slimey'],
  },
  {
    artist_name: 'Dylvinci',
    style_description: `Dylvinci is an underground SoundCloud artist whose name references the Renaissance master and whose music aspires to a similar sense of craft and beauty within the plugg underground. His beats feature more elaborately constructed melodic elements than typical plugg music — synth arrangements that feel genuinely musical rather than simply atmospheric. BPMs fall between 70 and 85. Dylvinci represents artists in the SoundCloud underground who bring genuine musical ambition to the genre, attempting to make beats that are beautiful in a conventional musical sense while maintaining the essential lo-fi, underground credibility of plugg. His production has an elegance that distinguishes it from more deliberately raw aesthetics.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Elegant', 'Melodic', 'Dark', 'Beautiful'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Jaydes', 'Okaymar'],
  },
  {
    artist_name: 'Kxngrada',
    style_description: `Kxngrada is an underground SoundCloud artist who brings a royal, elevated sensibility to the rage and plugg aesthetic. The "king" reference in his name suggests an artist who approaches the underground with a sense of authority and self-assurance rather than the vulnerability typical of much plugg music. BPMs fall between 75 and 95. His beats carry more confidence and presence than the most melancholy plugg production, with 808 patterns that feel commanding and melodic loops that project strength rather than sadness. Kxngrada represents artists who use the underground's sonic tools to communicate power and confidence rather than emotional vulnerability.`,
    associated_genres: ['Rage', 'Plugg', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Confident', 'Dark', 'Powerful', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Rexv2', 'Slayr', 'Nine Vicious'],
  },
  {
    artist_name: 'JJ1da',
    style_description: `JJ1da is an underground SoundCloud artist working in the plugg and rage tradition with a distinctive personal style that blends slow, atmospheric production with a conversational, stream-of-consciousness vocal approach. His beats feature the characteristic elements of plugg (slow 808, reverb melody, minimal drums) while creating space for a more naturalistic and less melodically processed vocal performance. BPMs fall between 70 and 85. JJ1da represents artists who use the underground's atmospheric production to create intimate, conversational music that feels like private thoughts being shared rather than performed.`,
    associated_genres: ['Plugg', 'Rage', 'Introspective Rap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Conversational', 'Intimate', 'Dark', 'Personal'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Milan', 'Izaya Tiji', 'Osamason'],
  },
  {
    artist_name: 'Perc40',
    style_description: `Perc40 is an underground SoundCloud artist whose name references pharmaceutical culture and whose music reflects the drug-influenced aesthetic of much plugg and rage music. His beats have a particularly intoxicated, sluggish quality — 808 patterns that feel like they are struggling to maintain their own momentum, melodies that drift rather than move with purpose. BPMs fall between 60 and 80. Perc40 represents the most explicitly substance-influenced corner of the plugg underground, where the music is designed to mirror and amplify altered states of consciousness. The production creates a specific feeling of pleasant numbness that has become one of the genre's defining emotional textures.`,
    associated_genres: ['Plugg', 'Rage', 'Lo-Fi Trap'],
    typical_bpm_range: '60-80',
    mood_tags: ['Sluggish', 'Numb', 'Dreamy', 'Hazy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Yhapojj', 'Osamason', '1oneam'],
  },
  {
    artist_name: 'Smokingskul',
    style_description: `Smokingskul is an underground SoundCloud artist who blends plugg and rage aesthetics with dark, gothic imagery and sonic elements that push the genre toward its most menacing extreme. His beats feature ominous melodic loops, heavily distorted 808 bass, and a production aesthetic that feels genuinely threatening — as if something dangerous is lurking beneath the atmospheric surface. BPMs fall between 70 and 90. Smokingskul represents the intersection of the plugg underground and gothic trap aesthetics, creating music where the dreamlike quality of plugg becomes a vehicle for dread rather than sadness. His production has a cinematic darkness that connects to horror film scoring and dark ambient music.`,
    associated_genres: ['Plugg', 'Dark Trap', 'Gothic Rap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Gothic', 'Dark', 'Menacing', 'Horror'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Black Kray', 'Sickboyrari', 'KP Beats'],
  },
  {
    artist_name: 'Wildkarduno',
    style_description: `Wildkarduno is an underground SoundCloud artist whose name signals an unpredictable, wildcard energy that is reflected in music that doesn't follow predictable patterns or genre conventions. His beats blend elements of plugg, rage, and more eclectic influences into a sound that feels genuinely hard to categorize. BPMs fall between 70 and 100 depending on the track. Wildkarduno represents artists in the SoundCloud underground who refuse to be pinned to a single aesthetic, moving fluidly between moods and styles while maintaining an overall underground sensibility. His production reflects a restless creativity that keeps listeners genuinely uncertain about where the music will go next.`,
    associated_genres: ['Plugg', 'Rage', 'Experimental'],
    typical_bpm_range: '70-100',
    mood_tags: ['Unpredictable', 'Dark', 'Chaotic', 'Energetic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Dragnutz', 'Xaviersobased', 'Luracks'],
  },
  {
    artist_name: 'Diego Money',
    style_description: `Diego Money is an underground SoundCloud artist who brings a Latin-influenced perspective to the plugg and rage aesthetic, blending the genre's characteristic slow, atmospheric production with melodic sensibilities drawn from Latin trap and reggaeton. BPMs fall between 75 and 95. His music creates an interesting cultural synthesis where the minimalism of SoundCloud underground production meets the melodic richness of Latin music traditions. Diego Money represents artists who are expanding the geographic and cultural range of the plugg underground beyond its primarily American Black cultural roots.`,
    associated_genres: ['Plugg', 'Rage', 'Latin Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Melodic', 'Dark', 'Cultural', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'BabyBartier'],
  },
  {
    artist_name: 'Sk8Star',
    style_description: `Sk8Star is an underground SoundCloud artist whose name and aesthetic are deeply connected to skate culture and its intersection with rap, punk, and DIY creative traditions. His music blends plugg and rage production with a rawer, more physically kinetic energy that reflects the speed and recklessness of skating. BPMs tend to be on the higher end of the rage spectrum at 85-110. The production has a rougher, more abrasive quality than typical soft plugg — beats that feel like they could accompany a skating video, carrying momentum and impact rather than stillness and contemplation.`,
    associated_genres: ['Rage', 'Skate Rap', 'Trap'],
    typical_bpm_range: '85-110',
    mood_tags: ['Energetic', 'Raw', 'Dark', 'Kinetic'],
    underground_level: 9,
    era: '2021-present',
    similar_artists: ['LazerDim700', 'Tezzus', 'Bktherula'],
  },
  {
    artist_name: 'RealYungPhil',
    style_description: `RealYungPhil is an underground SoundCloud artist whose music reflects the emotional complexities of youth — music that is simultaneously carefree and deeply troubled, energetic and despairing. His beats blend plugg atmospheric qualities with a more youthful, playful energy, creating a sound that feels like the intersection of teenage recklessness and genuine emotional pain. BPMs fall between 75 and 95. RealYungPhil represents artists who bring a distinctly young perspective to the underground, using the genre's tools to process the specific emotional landscape of adolescence and early adulthood.`,
    associated_genres: ['Plugg', 'Rage', 'SoundCloud Rap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Youthful', 'Emotional', 'Dark', 'Energetic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Osamason', 'Fakemink'],
  },
  {
    artist_name: 'KA$HDAMI',
    style_description: `KA$HDAMI is an underground SoundCloud artist who blends plugg and rage aesthetics with a hustle-forward narrative that connects the atmospheric underground sound to more explicitly material and aspirational themes. His beats feature slow 808 patterns and dark melodies characteristic of the plugg underground alongside a musical energy that reflects drive and ambition rather than pure emotional vulnerability. BPMs fall between 75 and 95. KA$HDAMI represents artists who use the SoundCloud underground's sonic tools to tell stories of financial ambition and street entrepreneurship, expanding the genre's thematic range.`,
    associated_genres: ['Plugg', 'Rage', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Driven', 'Dark', 'Ambitious', 'Energetic'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['CashCache', 'Nino Paid', 'Boolymon'],
  },
  {
    artist_name: 'WiFiGawd',
    style_description: `WiFiGawd is a pioneering figure of the SoundCloud cloud rap and plugg movement from the mid-2010s, known for being one of the early artists to develop the aesthetic that would become the template for the entire 2020s plugg underground. His production features extremely spacious, reverb-heavy beats — 808s with long decay, ambient synth textures, and drum patterns so minimal they barely register as percussion. BPMs typically fall between 70 and 90. WiFiGawd's work is defined by the same spatial openness his name suggests: music that feels like it exists in an infinite digital space, unmoored from physical or geographic constraints. He has worked extensively with Ethereal and other artists in the Atlanta underground ecosystem, and his influence on the entire plugg genre is foundational.`,
    associated_genres: ['Cloud Rap', 'Plugg', 'SoundCloud Rap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Spacious', 'Ethereal', 'Dark', 'Floating'],
    underground_level: 10,
    era: '2014-present',
    similar_artists: ['Ethereal', 'MexikoDro', 'Black Kray', 'Osamason'],
  },
  {
    artist_name: 'Acid Souljah',
    style_description: `Acid Souljah is an underground SoundCloud artist whose name references both the acid house music tradition and a warlike self-presentation, creating an interesting tension between electronic music history and rap aggression. His beats blend plugg atmospheric elements with a more psychedelic, distorted production style that sounds genuinely acid-warped. BPMs fall between 70 and 95. Acid Souljah represents the psychedelic wing of the plugg underground, where the genre's dreamy qualities are pushed toward more explicitly hallucinatory territory — music that sounds like a trip rather than a mood.`,
    associated_genres: ['Plugg', 'Rage', 'Psychedelic Trap'],
    typical_bpm_range: '70-95',
    mood_tags: ['Psychedelic', 'Dark', 'Warped', 'Aggressive'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Xaviersobased', 'Fakemink', 'Dragnutz'],
  },
  {
    artist_name: 'Tony 2Milli',
    style_description: `Tony 2Milli is an underground SoundCloud artist who brings a numerical precision and ambition reflected in his name to the plugg and rage aesthetic. His music blends atmospheric plugg production with themes of financial success and upward mobility, creating a sound where the underground's introspective qualities serve as backdrop for aspirational narratives. BPMs fall between 75 and 95. His beats carry both darkness and drive — production that feels simultaneously contemplative and motivated, appropriate for music about working toward something specific while navigating difficult circumstances.`,
    associated_genres: ['Plugg', 'Rage', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Ambitious', 'Dark', 'Driven', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['CashCache', 'KA$HDAMI', 'Nino Paid'],
  },
  {
    artist_name: 'Niontay',
    style_description: `Niontay is an underground SoundCloud rapper known for sharp wit, layered wordplay, and an ironic sensibility that distinguishes his music from the more earnestly emotional plugg underground. His production blends cloud rap and plugg aesthetics with a more intellectually playful approach — beats that are spacious and atmospheric but serve a rapping style that is technically sophisticated and lyrically dense. BPMs fall between 80 and 100. Niontay represents artists who bring genuine lyrical craft to the SoundCloud underground, creating music where the production's atmospheric qualities create space for complex ideas rather than pure emotional expression. He has developed a cult following for his ability to be simultaneously funny and profound.`,
    associated_genres: ['Underground Hip-Hop', 'Cloud Rap', 'SoundCloud Rap'],
    typical_bpm_range: '80-100',
    mood_tags: ['Witty', 'Dark', 'Intellectual', 'Atmospheric'],
    underground_level: 10,
    era: '2018-present',
    similar_artists: ['WiFiGawd', 'MexikoDro', 'Black Kray'],
  },
  {
    artist_name: 'Bear1Boss',
    style_description: `Bear1Boss is an underground SoundCloud artist who brings a larger-than-life, dominant energy to the plugg and rage aesthetic. The "boss" energy in his name reflects music that carries authority and presence rather than vulnerability — beats where the slow plugg tempo serves a commanding rather than mournful purpose. BPMs fall between 75 and 95. His production has more rhythmic drive and presence than typical minimal plugg, with 808 patterns that feel intentionally heavy and dominant. Bear1Boss represents artists who repurpose the underground's sonic tools to convey strength and power rather than the emotional softness that characterizes much plugg music.`,
    associated_genres: ['Rage', 'Plugg', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Dominant', 'Dark', 'Powerful', 'Heavy'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Kxngrada', 'Boolymon', 'Slayr'],
  },
  {
    artist_name: 'Tana',
    style_description: `Tana is an underground SoundCloud artist whose music occupies the emotional and atmospheric space between plugg's introspective sadness and a more romantically charged melodic sensibility. His beats feature slow 808 patterns and reverb-heavy melodic loops with a warmth and sweetness that distinguishes his sound from colder, more desolate plugg aesthetics. BPMs fall between 70 and 85. Tana represents artists who bring romantic themes and warm emotional textures to the plugg underground, creating music that is melancholy but not bleak — sad in the way that beautiful things can be sad rather than in the way that painful things are.`,
    associated_genres: ['Plugg', 'Rage', 'Melodic Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Romantic', 'Warm', 'Melancholy', 'Sweet'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Nettspend', 'Jaeychino', 'Prettifun'],
  },
  {
    artist_name: 'Muddymya',
    style_description: `Muddymya is an underground SoundCloud artist whose name reflects the murky, lo-fi aesthetic that defines her production approach. Her beats feature deliberately muddied sonic textures — low-end heavy mixes where individual elements blur together into a cloudy, atmospheric whole. BPMs fall between 65 and 85. Muddymya represents artists who treat the lo-fi qualities of the plugg underground as a deliberate aesthetic choice rather than a technical limitation — music where the mud is the point, where sonic imperfection creates emotional authenticity. Her production demonstrates how the SoundCloud underground has made intentional lo-fi a sophisticated artistic choice.`,
    associated_genres: ['Plugg', 'Lo-Fi Trap', 'Rage'],
    typical_bpm_range: '65-85',
    mood_tags: ['Murky', 'Dark', 'Lo-Fi', 'Atmospheric'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Bleood', 'ohsxnta', 'Osamason'],
  },
  {
    artist_name: 'Sojabrat',
    style_description: `Sojabrat is an underground SoundCloud artist who blends plugg and rage aesthetics with a bratty, transgressive energy that refuses to take the genre's emotional gravitas entirely seriously. His music is playful and irreverent even as it operates within the dark, atmospheric plugg framework — creating a productive tension between the format's typical seriousness and a more chaotic, joking persona. BPMs fall between 75 and 95. Sojabrat represents artists who bring humor and irreverence to the SoundCloud underground, creating music that subverts expectations while remaining unmistakably rooted in the genre's sonic traditions.`,
    associated_genres: ['Plugg', 'Rage', 'SoundCloud Rap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Playful', 'Irreverent', 'Dark', 'Chaotic'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Xaviersobased', 'Fakemink', 'Osamason'],
  },
  {
    artist_name: 'Bktherula',
    style_description: `Bktherula is an Atlanta-based SoundCloud rapper known for an intensely energetic, chaotic style that operates at the intersection of rage music, trap, and hyperpop. Her music is characterized by rapid-fire vocal delivery, highly pitched production elements, and a general sense of maximum energy that distinguishes her from the slower, more melancholic end of the rage underground. BPMs fall between 100 and 140. Bktherula has developed a significant following for music that feels genuinely unhinged in the best possible way — production that barely contains her enormous energy. She represents the most high-velocity and anarchic wing of the Atlanta SoundCloud scene, where rage aesthetics are pushed to their most extreme and physically energetic expression. Key features: high-energy drums, pitched production elements, chaotic structure, maximum intensity.`,
    associated_genres: ['Rage', 'Hyperpop', 'Atlanta Trap'],
    typical_bpm_range: '100-140',
    mood_tags: ['Chaotic', 'Energetic', 'Dark', 'Intense'],
    underground_level: 8,
    era: '2021-present',
    similar_artists: ['Homixide Gang', 'UnoTheActivist', 'LazerDim700', 'Tezzus'],
  },
  {
    artist_name: 'Fimiguerrero',
    style_description: `Fimiguerrero is an underground SoundCloud artist who brings a multicultural, genre-fluid perspective to the rage and plugg aesthetic. His production incorporates influences from Latin music, Afrobeats, and various global music traditions alongside the plugg framework, creating beats that feel simultaneously underground American and globally informed. BPMs fall between 70 and 95. Fimiguerrero represents artists who are genuinely expanding the cultural vocabulary of the plugg underground by drawing from musical traditions beyond its established American influences. His production has an warmth and rhythmic complexity that distinguishes it from more purely minimalist plugg aesthetics.`,
    associated_genres: ['Plugg', 'Rage', 'Global Trap'],
    typical_bpm_range: '70-95',
    mood_tags: ['Warm', 'Cultural', 'Melodic', 'Dark'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Diego Money', 'Osamason', 'Nettspend'],
  },
  {
    artist_name: 'Feng',
    style_description: `Feng is an underground SoundCloud artist whose single-name identity suggests a minimalist, almost zen approach to the plugg and rage aesthetic. His beats feature extremely spare production — single melodic elements, slow 808 patterns, and an economy of means that creates maximum emotional impact from minimum sonic material. BPMs fall between 60 and 80. Feng represents the most contemplative and meditative end of the SoundCloud underground, where the music approaches a kind of stillness that feels genuinely unusual in the rap context. The production creates space for deep listening and genuine emotional processing.`,
    associated_genres: ['Plugg', 'Ambient Trap', 'Rage'],
    typical_bpm_range: '60-80',
    mood_tags: ['Minimal', 'Meditative', 'Dark', 'Still'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Maajins', 'R8', 'Yhapojj'],
  },
  {
    artist_name: 'EsDeeKid',
    style_description: `EsDeeKid is an underground SoundCloud artist whose name suggests a youthful, SD-card-era digital native sensibility. His music reflects the aesthetic of someone who grew up with digital music production tools — beats that embrace the digital texture and lo-fi qualities of home recording as expressive elements rather than technical limitations. BPMs fall between 70 and 90. EsDeeKid represents the generation of producers who learned to make music from tutorials and SoundCloud itself, creating an aesthetic that is genuinely self-taught and raw. His production has a homemade quality that is central to its emotional authenticity.`,
    associated_genres: ['Plugg', 'Rage', 'Lo-Fi Trap'],
    typical_bpm_range: '70-90',
    mood_tags: ['Raw', 'Digital', 'Dark', 'Youthful'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Bleood', 'R8', 'Osamason'],
  },
  {
    artist_name: 'Ledbyher',
    style_description: `Ledbyher is an underground SoundCloud artist whose name suggests music that follows female guidance or inspiration — production that is devoted, vulnerable, and emotionally open in ways that challenge conventional masculine rap presentation. His beats feature slow, gentle melodic loops, soft 808 patterns, and a production aesthetic that prioritizes emotional openness over toughness or aggression. BPMs fall between 65 and 80. Ledbyher represents artists who use the plugg underground's atmospheric tools to express a genuine emotional vulnerability and romantic devotion, creating music that feels rare and honest.`,
    associated_genres: ['Plugg', 'Rage', 'Romantic Trap'],
    typical_bpm_range: '65-80',
    mood_tags: ['Vulnerable', 'Romantic', 'Gentle', 'Melancholy'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Izaya Tiji', 'Milan', 'Tana'],
  },
  {
    artist_name: 'Jim Legxacy',
    style_description: `Jim Legxacy is an underground SoundCloud artist whose name references both a classic first name and the concept of legacy — music made with an awareness of leaving something lasting in the underground. His production blends plugg atmospheric elements with a more considered, deliberate approach that suggests someone building toward something rather than simply expressing a mood. BPMs fall between 75 and 95. Jim Legxacy represents artists who approach the underground with long-term creative ambition, making music that feels like part of a larger artistic project rather than a series of disconnected SoundCloud drops.`,
    associated_genres: ['Plugg', 'Rage', 'Underground Hip-Hop'],
    typical_bpm_range: '75-95',
    mood_tags: ['Ambitious', 'Dark', 'Deliberate', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Kxngrada'],
  },
  {
    artist_name: 'Snoa',
    style_description: `Snoa is an underground SoundCloud artist whose name evokes a quietly observed scene — music that watches and reflects rather than performing or asserting. His production features the atmospheric plugg framework applied with a contemplative, observational sensibility — beats that feel like they are looking at something from a distance rather than being in the middle of it. BPMs fall between 65 and 80. Snoa represents the most introspective and quietly observational corner of the plugg underground, where the music creates the feeling of watching something pass rather than participating in it.`,
    associated_genres: ['Plugg', 'Ambient Trap', 'Rage'],
    typical_bpm_range: '65-80',
    mood_tags: ['Contemplative', 'Quiet', 'Dark', 'Observational'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Maajins', 'Feng', '1oneam'],
  },
  {
    artist_name: 'Blimeydog',
    style_description: `Blimeydog is an underground SoundCloud artist whose British exclamation in the name suggests a cross-cultural perspective — the American plugg and rage aesthetic filtered through a non-American sensibility. His production blends the SoundCloud underground framework with subtle references to UK grime and drill traditions, creating a hybrid that feels genuinely transatlantic. BPMs fall between 70 and 95. Blimeydog represents the international dimension of the plugg underground, where the genre's American origins are being absorbed and reinterpreted by artists from different cultural contexts.`,
    associated_genres: ['Plugg', 'Rage', 'UK-Influenced Trap'],
    typical_bpm_range: '70-95',
    mood_tags: ['Dark', 'Cultural', 'Atmospheric', 'Cold'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Osamason', 'Nettspend', 'Untiljapan'],
  },
  {
    artist_name: 'Llondon Actress',
    style_description: `Llondon Actress is an underground SoundCloud artist whose double-L spelling and theatrical name suggest a deliberately constructed persona — music as performance and identity creation. Her production blends plugg atmospheric elements with a more explicitly theatrical and cinematic quality, as if each beat is a scene in a larger narrative. BPMs fall between 70 and 85. Llondon Actress represents artists who approach the underground with a conceptual and artistic framework beyond pure emotional expression — music made with a sense of character, narrative, and performance that transforms the genre's raw emotional materials into something more deliberately crafted.`,
    associated_genres: ['Plugg', 'Rage', 'Art Trap'],
    typical_bpm_range: '70-85',
    mood_tags: ['Theatrical', 'Dark', 'Cinematic', 'Constructed'],
    underground_level: 10,
    era: '2022-present',
    similar_artists: ['Pradabagshawty', 'Prettifun', 'Osamason'],
  },
  {
    artist_name: 'Homixide Gang',
    style_description: `Homixide Gang (Homixide Meechie and Homixide G-Weed) are Atlanta artists associated with Gunna and the 4PF/YSL ecosystem who blend rage aesthetics with harder, more aggressive trap. Their production aesthetic features very fast hi-hat rolls, sharp snare claps, and 808s that are more punchy and present than the slow plugg style. BPMs range from 100 to 140, making their beats among the most energetic in the rage-adjacent space. Sonically they bridge the gap between mainstream Atlanta trap and the underground rage scene — beats that have the sonic intensity of plugg music but the rhythmic drive of hard trap. They are a core reference point for aggressive, high-energy Atlanta underground music and have influenced a generation of artists who want to maintain underground credibility while delivering music with real physical impact. Key features: rapid hi-hat patterns, heavy snare, punchy 808, intense energy.`,
    associated_genres: ['Rage', 'Trap', 'Atlanta Hip-Hop'],
    typical_bpm_range: '100-140',
    mood_tags: ['Aggressive', 'Dark', 'Energetic', 'Hard'],
    underground_level: 7,
    era: '2021-present',
    similar_artists: ['Bktherula', 'LazerDim700', 'UnoTheActivist', 'Tezzus'],
  },
  {
    artist_name: 'ApolloRed',
    style_description: `ApolloRed is an underground SoundCloud artist whose name combines classical mythology with a bold color, suggesting an artist who approaches the underground with ambition and visual boldness. His music blends plugg atmospheric elements with a more confident, assertive energy than typical melancholy plugg — beats that feel elevated and aspiring rather than sunken and introspective. BPMs fall between 75 and 95. ApolloRed represents artists who bring a sense of grandeur and scale to the underground, using the plugg framework to make music that feels larger and more ambitious than its intimate production origins might suggest.`,
    associated_genres: ['Rage', 'Plugg', 'Trap'],
    typical_bpm_range: '75-95',
    mood_tags: ['Ambitious', 'Dark', 'Confident', 'Atmospheric'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Kxngrada', 'Jim Legxacy', 'Osamason'],
  },
  {
    artist_name: 'DMV Crank',
    style_description: `DMV Crank is an artist rooted in the DMV (DC, Maryland, Virginia) music scene who brings the regional go-go and DC rap traditions into contact with contemporary SoundCloud underground aesthetics. His music reflects the specific musical heritage of the DMV region — the driving rhythms of go-go percussion mixed with the atmospheric plugg aesthetic — creating a sound that is simultaneously regionally specific and universally underground. BPMs fall between 80 and 110. DMV Crank represents the regional diversity of the SoundCloud underground, showing how the genre's basic framework can absorb and reflect different geographic and cultural origins.`,
    associated_genres: ['DMV Rap', 'Plugg', 'Trap'],
    typical_bpm_range: '80-110',
    mood_tags: ['Regional', 'Dark', 'Energetic', 'Cultural'],
    underground_level: 9,
    era: '2021-present',
    similar_artists: ['Osamason', 'LazerDim700', 'Tezzus'],
  },
  {
    artist_name: 'Ethereal',
    style_description: `Ethereal is an Atlanta-based rapper and producer who is one of the originators of the plugg and rage aesthetic, with a career stretching back to the early 2010s. His production style features ghostly, hollow synth textures, cavernous 808 bass, and a deeply melancholic atmosphere that predates and influenced the entire current plugg underground. BPMs range from 65 to 90. Ethereal's beats have a spectral quality — music that seems to exist in a liminal space between the physical and the digital, between the real and the imagined. He is closely associated with Awful Records and the Atlanta experimental rap scene, bringing an anti-commercial, artistically adventurous sensibility to his production. His foundational influence on the current generation of SoundCloud underground artists cannot be overstated. Key features: hollow reverb on all elements, spectral synth melodies, deep distorted 808, slow rolling hi-hat triplets.`,
    associated_genres: ['Plugg', 'Rage', 'Experimental Trap'],
    typical_bpm_range: '65-90',
    mood_tags: ['Ethereal', 'Dark', 'Atmospheric', 'Melancholy'],
    underground_level: 9,
    era: '2012-present',
    similar_artists: ['WiFiGawd', 'MexikoDro', 'Black Kray', 'Osamason'],
  },
  {
    artist_name: 'Black Kray',
    style_description: `Black Kray is a pioneering figure of the SoundCloud underground and one of the originators of the goth trap and plugg aesthetic. His music blends dark, melancholic 808 production with vocal performances that carry genuine despair, creating an aesthetic that was radically original when it emerged and has since influenced hundreds of artists. His production features slow, dragging 808 patterns, minor-key melodic elements, and a lo-fi mixing aesthetic that makes everything sound simultaneously beautiful and decayed. BPMs typically fall between 65 and 85. Black Kray's work drew from Memphis rap, Three 6 Mafia aesthetics, and early 2010s SoundCloud experimentation to create a template for gothic underground rap that remains vital. He represents the original vision of what dark SoundCloud rap could be — raw, emotionally devastated, and genuinely original. Key features: slow 808, minor-key melodies, gothic atmosphere, lo-fi production.`,
    associated_genres: ['Plugg', 'Gothic Trap', 'SoundCloud Rap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Gothic', 'Dark', 'Melancholy', 'Raw'],
    underground_level: 10,
    era: '2014-present',
    similar_artists: ['Ethereal', 'WiFiGawd', 'MexikoDro', 'Smokingskul'],
  },
  {
    artist_name: 'Sickboyrari',
    style_description: `Sickboyrari is a SoundCloud artist known for occupying the intersection of rage, hyperpop, and emo rap with a production aesthetic that emphasizes chaos, color, and emotional extremity. His beats feature pitched-up synths, distorted 808 bass, and production elements drawn from both plugg minimalism and hyperpop maximalism, creating a sound that refuses to stay still or be easily categorized. BPMs range from 80 to 120. Sickboyrari has collaborated with artists including Lil Tracy and others in the SoundCloud emo-rap underground, bringing a genuinely experimental and emotionally raw quality to his work. His aesthetic is deliberately destabilizing — music that sounds like it is falling apart even as it maintains a compelling forward motion. Key features: hyperpop-influenced production, pitched elements, rage aesthetic, emotional extremity.`,
    associated_genres: ['Rage', 'Hyperpop', 'Emo Trap'],
    typical_bpm_range: '80-120',
    mood_tags: ['Chaotic', 'Emotional', 'Dark', 'Experimental'],
    underground_level: 9,
    era: '2017-present',
    similar_artists: ['Black Kray', 'Xaviersobased', 'Fakemink', 'Smokingskul'],
  },
  {
    artist_name: 'UnoTheActivist',
    style_description: `UnoTheActivist is an Atlanta rapper known for energetic, melodic delivery over trap production that carries both atmospheric depth and genuine rhythmic drive. His production aesthetic combines the spaciousness of cloud rap and plugg with more energetic trap elements — beats that create emotional atmosphere while maintaining enough rhythmic propulsion for active, engaging performances. BPMs typically fall between 100 and 130. Uno has worked with artists including Playboi Carti and others in the Atlanta underground-to-commercial pipeline, representing a generation of Atlanta artists who bridged the gap between underground SoundCloud culture and wider recognition. His music has a distinctive energy that makes it feel alive and spontaneous even in studio-recorded form. Key features: melodic delivery, atmospheric trap production, mid-to-high BPM, emotional expressiveness.`,
    associated_genres: ['Melodic Trap', 'Atlanta Hip-Hop', 'SoundCloud Rap'],
    typical_bpm_range: '100-130',
    mood_tags: ['Energetic', 'Melodic', 'Dark', 'Expressive'],
    underground_level: 7,
    era: '2016-present',
    similar_artists: ['Homixide Gang', 'Bktherula', 'LazerDim700', 'Ethereal'],
  },
  {
    artist_name: 'Hardrock',
    style_description: `Hardrock is an underground SoundCloud artist whose name signals an aesthetic that pushes the plugg and rage framework toward its hardest and most physically impactful extreme. His beats feature heavier drums than typical plugg music, more distorted and present 808 bass, and a general production aesthetic that prioritizes physical impact over atmospheric dreaminess. BPMs fall between 80 and 110. Hardrock represents artists who take the underground's sonic vocabulary and use it to make genuinely hard, physically compelling music — beats that hit rather than float, that demand physical response rather than contemplative reflection.`,
    associated_genres: ['Rage', 'Trap', 'Dark Rap'],
    typical_bpm_range: '80-110',
    mood_tags: ['Hard', 'Dark', 'Aggressive', 'Physical'],
    underground_level: 9,
    era: '2022-present',
    similar_artists: ['Slayr', 'Nine Vicious', 'Homixide Gang'],
  },
  {
    artist_name: 'Phreshboyswag',
    style_description: `Phreshboyswag is an underground SoundCloud rapper known for bringing a carefree, confident "swag" aesthetic into dialogue with the deeper emotional currents of the plugg underground. His music has a looser, more playful quality than typical melancholy plugg — beats with more rhythmic bounce and less atmospheric heaviness — while still operating within the SoundCloud underground aesthetic framework. BPMs fall between 80 and 100. Phreshboyswag represents artists who bring lightness and self-assurance to the underground, creating music that is cool and pleasurable rather than primarily dark or contemplative. His production has an effortless, natural quality that makes the music feel like it was made without effort, even when it wasn't.`,
    associated_genres: ['SoundCloud Rap', 'Plugg', 'Cloud Rap'],
    typical_bpm_range: '80-100',
    mood_tags: ['Carefree', 'Cool', 'Swaggering', 'Light'],
    underground_level: 9,
    era: '2019-present',
    similar_artists: ['WiFiGawd', 'MexikoDro', 'Osamason'],
  },
  {
    artist_name: 'Sniper2004',
    style_description: `Sniper2004 is an underground SoundCloud artist whose name suggests both precision and a specific birth year, placing him among the youngest artists in the plugg underground — music made by someone who grew up with the genre rather than helping create it. His beats reflect a deep fluency in plugg and rage conventions, applied with the confidence of someone for whom this is simply the native musical language. BPMs fall between 65 and 85. Sniper2004 represents the next generation of the SoundCloud underground — artists who absorbed the genre's conventions so completely that they can use them with genuine mastery. His production has the hallmarks of deep genre literacy: slow 808, reverb melody, minimal drums, applied with the precision his name suggests.`,
    associated_genres: ['Plugg', 'Rage', 'SoundCloud Rap'],
    typical_bpm_range: '65-85',
    mood_tags: ['Precise', 'Dark', 'Melancholy', 'Atmospheric'],
    underground_level: 10,
    era: '2023-present',
    similar_artists: ['Nettspend', 'Osamason', 'Yhapojj'],
  },
]

async function getEmbedding(text: string): Promise<number[]> {
  const response = await openai.embeddings.create({
    model: 'text-embedding-3-small',
    input: text,
  })
  return response.data[0].embedding
}

async function seed() {
  console.log(`Seeding ${ARTISTS.length} artists into music_knowledge...`)

  let successCount = 0
  let errorCount = 0

  for (let i = 0; i < ARTISTS.length; i++) {
    const artist = ARTISTS[i]
    try {
      process.stdout.write(`[${i + 1}/${ARTISTS.length}] ${artist.artist_name}... `)

      const embedding = await getEmbedding(artist.style_description)

      const { error } = await supabase.from('music_knowledge').upsert(
        {
          artist_name: artist.artist_name,
          style_description: artist.style_description,
          associated_genres: artist.associated_genres,
          typical_bpm_range: artist.typical_bpm_range,
          mood_tags: artist.mood_tags,
          underground_level: artist.underground_level,
          era: artist.era,
          similar_artists: artist.similar_artists,
          embedding,
        },
        { onConflict: 'artist_name' }
      )

      if (error) {
        console.log(`ERROR: ${error.message}`)
        errorCount++
      } else {
        console.log('OK')
        successCount++
      }

      await new Promise((r) => setTimeout(r, 350))
    } catch (err) {
      console.log(`EXCEPTION: ${err}`)
      errorCount++
    }
  }

  console.log(`\nDone. ${successCount} succeeded, ${errorCount} failed.`)
}

seed().catch(console.error)
