import type { Beat, Profile } from '@/types'

export const DEMO_PRODUCERS: Profile[] = [
  {
    id: 'demo-prod-1',
    username: 'metro_wavez',
    display_name: 'Metro Wavez',
    avatar_url: 'https://picsum.photos/seed/prod1/200/200',
    banner_url: null,
    bio: 'Trap / Drill beats that hit different 🎹',
    location: 'Atlanta, GA',
    role: 'producer',
    placements: ['Lil Baby', 'Future', '21 Savage'],
    instagram_url: null,
    discord_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-prod-2',
    username: 'drknght_prod',
    display_name: 'Dark Knight',
    avatar_url: 'https://picsum.photos/seed/prod2/200/200',
    banner_url: null,
    bio: 'Dark melodic trap. UK Drill. No cap.',
    location: 'London, UK',
    role: 'producer',
    placements: ['Central Cee'],
    instagram_url: null,
    discord_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-prod-3',
    username: 'lo_fi_luna',
    display_name: 'Luna Beats',
    avatar_url: 'https://picsum.photos/seed/prod3/200/200',
    banner_url: null,
    bio: 'Lo-fi chill vibes for late nights 🌙',
    location: 'Los Angeles, CA',
    role: 'producer',
    placements: [],
    instagram_url: null,
    discord_url: null,
    created_at: new Date().toISOString(),
  },
]

export const DEMO_BEATS: Beat[] = [
  {
    id: 'demo-beat-1',
    producer_id: 'demo-prod-1',
    title: 'Midnight Drip',
    bpm: 140,
    key: 'Am',
    genre: ['Trap', 'Drill'],
    mood: ['Dark', 'Hard'],
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    cover_url: 'https://picsum.photos/seed/beat1/800/800',
    video_url: null,
    description: null,
    duration_seconds: 180,
    plays: 12400,
    likes_count: 843,
    downloads_count: 291,
    created_at: new Date().toISOString(),
    producer: DEMO_PRODUCERS[0],
  },
  {
    id: 'demo-beat-2',
    producer_id: 'demo-prod-2',
    title: 'Ghost Protocol',
    bpm: 145,
    key: 'Dm',
    genre: ['UK Drill'],
    mood: ['Dark', 'Energetic'],
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    cover_url: 'https://picsum.photos/seed/beat2/800/800',
    video_url: null,
    description: null,
    duration_seconds: 210,
    plays: 8700,
    likes_count: 512,
    downloads_count: 178,
    created_at: new Date().toISOString(),
    producer: DEMO_PRODUCERS[1],
  },
  {
    id: 'demo-beat-3',
    producer_id: 'demo-prod-3',
    title: 'Stargazer',
    bpm: 85,
    key: 'G',
    genre: ['Lo-Fi'],
    mood: ['Chill', 'Melodic'],
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    cover_url: 'https://picsum.photos/seed/beat3/800/800',
    video_url: null,
    description: null,
    duration_seconds: 195,
    plays: 21000,
    likes_count: 1920,
    downloads_count: 640,
    created_at: new Date().toISOString(),
    producer: DEMO_PRODUCERS[2],
  },
  {
    id: 'demo-beat-4',
    producer_id: 'demo-prod-1',
    title: 'Neon Haze',
    bpm: 138,
    key: 'F#m',
    genre: ['Trap'],
    mood: ['Melodic', 'Hype'],
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    cover_url: 'https://picsum.photos/seed/beat4/800/800',
    video_url: null,
    description: null,
    duration_seconds: 168,
    plays: 5600,
    likes_count: 387,
    downloads_count: 112,
    created_at: new Date().toISOString(),
    producer: DEMO_PRODUCERS[0],
  },
  {
    id: 'demo-beat-5',
    producer_id: 'demo-prod-2',
    title: 'Cold Front',
    bpm: 150,
    key: 'Cm',
    genre: ['Drill', 'UK Drill'],
    mood: ['Dark', 'Hard'],
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    cover_url: 'https://picsum.photos/seed/beat5/800/800',
    video_url: null,
    description: null,
    duration_seconds: 225,
    plays: 9300,
    likes_count: 620,
    downloads_count: 205,
    created_at: new Date().toISOString(),
    producer: DEMO_PRODUCERS[1],
  },
]
