/**
 * Master list of artists producers commonly make type beats for.
 * Sorted alphabetically. Add new names here — the TypeBeatSelector picks them up automatically.
 */
export const TYPE_BEAT_ARTISTS: string[] = [
  // Mainstream
  '21 Savage',
  'A$AP Rocky',
  'Baby Keem',
  'Bladee',
  'Bones',
  'Bryson Tiller',
  'Cardi B',
  'Chris Brown',
  'Coi Leray',
  'Comethazine',
  'Cordae',
  'DaBaby',
  'Don Toliver',
  'Drake',
  'Ecco2k',
  'Fivio Foreign',
  'Future',
  'Ghostemane',
  'Gunna',
  'J. Cole',
  'Jack Harlow',
  'JID',
  'Juice WRLD',
  'Kendrick Lamar',
  'Kid Cudi',
  'Lil Baby',
  'Lil Durk',
  'Lil Peep',
  'Lil Tecca',
  'Lil TJay',
  'Lil Tracy',
  'Lil Uzi Vert',
  'Lil Yachty',
  'Mac Miller',
  'Megan Thee Stallion',
  'Nav',
  'NBA YoungBoy',
  'Night Lovell',
  'Playboi Carti',
  'Polo G',
  'Pop Smoke',
  'Post Malone',
  'Pouya',
  'Rod Wave',
  'Roddy Ricch',
  'Ski Mask The Slump God',
  'SZA',
  'Travis Scott',
  'Trippie Redd',
  'Tyler the Creator',
  'Wicca Phase Springs Eternal',
  'Wifisfuneral',
  'Xavier Wulf',
  'XXXTentacion',
  'Yeat',
  'Young Thug',
  '$uicideBoy$',

  // Underground / SoundCloud
  '1oneam',
  '1300Saint',
  '2Slimey',
  'Acid Souljah',
  'ApolloRed',
  'Autumn!',
  'BabyBartier',
  'Bear1Boss',
  'Black Kray',
  'Bleood',
  'Bktherula',
  'Blimeydog',
  'Boolymon',
  'CashCache',
  'Che',
  'Destroy Lonely',
  'Diego Money',
  'DMV Crank',
  'Dragnutz',
  'Dylvinci',
  'EsDeeKid',
  'Ethereal',
  'Fakemink',
  'Feng',
  'Fimiguerrero',
  'Glokk40Spaz',
  'Hardrock',
  'Homixide Gang',
  'Hxldr',
  'Izaya Tiji',
  'JJ1da',
  'Jaeychino',
  'Jaydes',
  'Jim Legxacy',
  'KA$HDAMI',
  'Ken Carson',
  'Karrahbooo',
  'Kxngrada',
  'Killstation',
  'LazerDim700',
  'Ledbyher',
  'Llondon Actress',
  'Luracks',
  'Maajins',
  'MexikoDro',
  'Milan',
  'Muddymya',
  'Nettspend',
  'Nine Vicious',
  'Nino Paid',
  'Niontay',
  'ohsxnta',
  'Okaymar',
  'Osamason',
  'Perc40',
  'Phreshboyswag',
  'Pradabagshawty',
  'Prettifun',
  'Pz\'',
  'R8',
  'RealYungPhil',
  'Rekover Jet',
  'Rexv2',
  'S3bby',
  'Sickboyrari',
  'Sk8Star',
  'Slayr',
  'Sniper2004',
  'Snoa',
  'Sojabrat',
  'SouthsideSilhouette',
  'SSGKobe',
  'Smokingskul',
  'StoopidXool',
  'Summrs',
  'Swapa',
  'Tana',
  'TDF',
  'Tezzus',
  'Tony 2Milli',
  'UnoTheActivist',
  'Untiljapan',
  'Wegonebeok',
  'WiFiGawd',
  'Wildkarduno',
  'Xaviersobased',
  'Yhapojj',
  'Yung Lean',

  // Genre & Style Labels (use like "Rage Type Beat", "Lo-Fi Type Beat")
  'Afrobeats',
  'Ambient',
  'Boom Bap',
  'Cloud Rap',
  'Dark',
  'Dark Trap',
  'Drill',
  'Dreamy',
  'Emo Rap',
  'Hard',
  'Hyperpop',
  'Jersey Club',
  'Latin Trap',
  'Lo-Fi',
  'Memphis',
  'Melodic',
  'Phonk',
  'Plugg',
  'R&B',
  'Rage',
  'Sad',
  'SoundCloud Rap',
  'Trap',
  'UK Drill',
]

/**
 * Returns artists whose name contains the query (case-insensitive).
 */
export function searchArtists(query: string, limit = 8): string[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  return TYPE_BEAT_ARTISTS.filter((a) => a.toLowerCase().includes(q)).slice(0, limit)
}
